version: 1
disable_existing_loggers: False

formatters:
  console_format:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  file_format:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

filters:
  important_only:
    (): src.utils.logger.ImportantLogFilter

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: console_format
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: file_format
    filename: data/logs/bitcoin_etl.log
    when: midnight
    interval: 1
    backupCount: 30
    encoding: utf-8
    filters: [important_only]

loggers:
  bitcoin_etl:
    level: INFO
    handlers: [console, file]
    propagate: False

root:
  level: INFO
  handlers: [console, file]
